### ISSUE TITLE
Error when installing the formats

### ISSUE THREAD

**Issue by TristanPouliquen** [ostrolucky/lnav-formats#1]
Hello,

I saw your repo on Symfony Slack and I find it awesome as I never took the time to dig into custom formats to use lnav with monolog!

I tried installing your formats on a V0.8.5 install of lnav, but when I then launch lnav I have this error:
```
error:monologjson:invalid sample         -- {"message":"Matched route "{route}".","context":{"route":"swagger_ui","route_parameters":{"_route":"swagger_ui","_controller":"api_platform.swagger_ui.action"},"request_uri":"http://localhost:8000/api/swagger","method":"GET"},"level":200,"level_name":"INFO","channel":"request","datetime":"2023-12-24T11:36:05.228749+00:00","extra":{}}
```

Have I done something wrong?

**Comment by ostrolucky** [comment]
I'm afraid 0.8.5 is too ancient. Please try with 0.11.x

**Comment by TristanPouliquen** [comment]
Ok thank you, sadly this is the version we get when installing it on an Ubuntu 22.04 :/
